In [1]:
import pandas as pd

In [2]:
print("clearned data  ")
df = pd.read_csv("titanic_cleaned.csv")

df.head()

clearned data

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [3]:
df["Sex"].head()

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object

In [4]:
df["Sex"].dtype

dtype('O')

In [5]:

df["Sex"] = df["Sex"].map({"male": 0, "female": 1})
df['Sex'].head()

0    0
1    1
2    1
3    1
4    0
Name: Sex, dtype: int64

In [6]:
# one hot encoding 
# Embarked,Pclass these are lables so i can do encoding

In [7]:
df= pd.get_dummies(df, columns=["Embarked", "Pclass" ] , drop_first=True)

In [8]:
df.head(20)

,Survived,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S,Pclass_2,Pclass_3
0,0,0,22.0,1,0,7.2500,False,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,False
2,1,1,26.0,0,0,7.9250,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,True,False,False
4,0,0,35.0,0,0,8.0500,False,True,False,True
5,0,0,28.0,0,0,8.4583,True,False,False,True
6,0,0,54.0,0,0,51.8625,False,True,False,False
7,0,0,2.0,3,1,21.0750,False,True,False,True
8,1,1,27.0,0,2,11.1333,False,True,False,True
9,1,1,14.0,1,0,30.0708,False,False,True,False
10,1,1,4.0,1,1,16.7000,False,True,False,True
11,1,1,58.0,0,0,26.5500,False,True,False,False
12,0,0,20.0,0,0,8.0500,False,True,False,True
13,0,0,39.0,1,5,31.2750,False,True,False,True
14,0,1,14.0,0,0,7.8542,False,True,False,True
15,1,1,55.0,0,0,16.0000,False,True,True,False
16,0,0,2.0,4,1,29.1250,True,False,False,True
17,1,0,28.0,0,0,13.0000,False,True,True,False
18,0,1,31.0,1,0,18.0000,False,True,False,True
19,1,1,28.0,0,0,7.2250,False,False,False,True

In [9]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Sex         891 non-null    int64
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Embarked_Q  891 non-null    bool
 7   Embarked_S  891 non-null    bool
 8   Pclass_2    891 non-null    bool
 9   Pclass_3    891 non-null    bool
dtypes: bool(4), float64(2), int64(4)
memory usage: 45.4 KB

Survived      0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked_Q    0
Embarked_S    0
Pclass_2      0
Pclass_3      0
dtype: int64

In [10]:
df.to_csv("titanic_data_modelready.csv", index=False)